name: This is Python 
on:
  push:
    branches:
      - main 

jobs:
  pythonimageecr:
    runs-on: myownrunners
    steps:  
      - name: Checkout code 
        uses: actions/checkout@v5  

      - name: Docker login 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.ECR_USER_NAME }}
          password: ${{ secrets.ECR_PASSWORD }}

      - name: Pull image from ECR
        run: docker pull 808932887013.dkr.ecr.ap-south-1.amazonaws.com/dev/pythonapplication:latest

      - name: Run container
        run: docker container run -d -P --name mypython 808932887013.dkr.ecr.ap-south-1.amazonaws.com/dev/pythonapplication:latest

      - name: Check container status
        run: docker ps
